# -*- coding: utf-8 -*-
"""
Created on Sun Dec 23 15:27:18 2018

@author: HEMTP
"""
from datetime import datetime
import feather
import pandas as pd
import numpy as np
import fuzz

Zcop1  = pd.read_excel("d:\\base.xlsx", sheet_name="Zcop")
ERD1 = pd.read_excel("d:\\base.xlsx", sheet_name="ERD")

CUSTNUM_LIST = ["20400"]

Zcop1['Project2'] = np.where(Zcop1['CUST_NUM'].isin(CUSTNUM_LIST), "Novartis EUS", "Novartis EUC") 

ERD1['ASSIGN_END'] = ERD1.ASSIGN_END.astype(str)

ERD1.rename(columns={'EMP_NO':'EMP_CODE', 'ASSIGN_END':'ERD_DATE'}, inplace=True)

ERD2 = ERD1[['EMP_CODE', 'ERD_DATE']]

ERD3 = ERD2.set_index('EMP_CODE').T.to_dict('list')

Zcop1['ERD_Date'] = Zcop1.EMP_CODE.map(ERD3)

Zcop2 = Zcop1[['LOAD_DATE',	'COM_CODE',	'COSTCTR',	'CC_DESC',	'SAP_BU_DESC',	'SAP_VERTICAL_DESC',	'CUST_NUM',	'CUST_NAME',	'PROJ_TYPE',	'WBS_CODE',	'DOM_ID',	'DOM_DESC',	'HOME_ORGUNIT',	'HOME_ORGUNIT_DESC',	'ORG_UNIT',	'ORG_UNIT_DESCRIPTION',	'Project2', 'PROJECT_CODE',	'STAFFING_PERCENTAGE',	'BILLABILITY_STATUS',	'EMP_CODE',	'EMP_NAME', 'ERD_Date',	'PM_ID',	'PM_NAME',	'TM_EMP_NO',	'TM_NAME',	'DERIVED_EMP_CITY',	'DERIVED_EMP_STATE',	'DERIVED_EMP_COUNTRY',	'DERIVED_EMP_GEOGRAPHY',	'ONS_OFF_FLAG',	'TOTAL_DAYS',	'AREA',	'ONSITE_DAYS',	'OFFSHORE_DAYS',	'BILLABLE',	'ONSITE_BILLABLE_DAYS',	'OFFSHORE_BILLABLE_DAYS',	'NON BILLABLE',	'ONSITE_NONBILLABLE_DAYS',	'OFFSHORE_NONBILLABLE_DAYS',	'SUPPORT',	'ONSITE_SERVICE_DAYS',	'OFFSHORE_SERVICE_DAYS',	'FREE',	'ONSITE_FREE_DAYS',	'OFFSHORE_FREE_DAYS',	'LEAVE_WHEN_BILLABLE_ONSITE',	'LEAVE_WHEN_BILLABLE_OFFSHORE',	'LEAVE_WHEN_NON_BILLABLE_ONSITE',	'LEAVE_WHEN_NON_BILLABLE_OFFSHORE',	'LEAVE_WHEN_FREE_ONSITE',	'LEAVE_WHEN_FREE_OFFSHORE',	'LEAVE_WHEN_SERVICE_ONSITE',	'LEAVE_WHEN_SERVICE_OFFSHORE',	'LEAVE_WHEN_OTHERS_ONSITE',	'LEAVE_WHEN_OTHERS_OFFSHORE',	'PRACTICE',	'PRAC_CC',	'PRAC_CC_DESC',	'SAP_PRAC_DESC',	'SAP_SUBPRAC_DESC',	'SEC_PRACTICE',	'SEC_PRAC_CC',	'SEC_PRAC_CC_DESC',	'SEC_SUPID',	'SUB_GEO',	'PREVIOUS_EXP_YRS',	'PREVIOUS_EXP_MON',	'WIPRO_EXP_YRS',	'WIPRO_EXP_MON',	'SOW_NO',	'LEAVE_STAT',	'INDICATOR',	'PERSONAL_AREA',	'PERSONAL_SUB_AREA',	'SUB_PRACTICE_DUAL_CREDIT',	'SUB_PRACTICE_DUAL_CREDIT_TEXT',	'CUSTOMER_ENGAGEMENT_TYPE',	'PROJECT_CLASSIFICATION',	'CAREER_BAND',	'START_DATE',	'END_DATE',	'CRMREFNO',	'PROJSTATUS',	'LOCATION',	'EMPLOYEE_EMAIL_ID',	'DATE_OF_JOINING',	'EXPERIENCE',	'BULGE',	'ROOKIE_STATUS',	'PRIMARY_SUPERVISOR',	'PROJECT_SUPERVISOR',	'CERTIFIED_SUITE',	'CERTIFIED_SKILL',	'POTENTIAL_SUITE',	'POTENTIAL_SKILL',	'UNASSESSED_SUITE',	'UNASSESSED_SKILL',	'PROJECT_ACQUIRED_SKILL',	'FLEXPROJ',	'NOCOST_LEAVEWHENBILLABLEONSITE',	'NOCOST_LEAVEWHENBILLABLEOFFSHORE',	'NOCOST_LEAVEWHENNONBILLABLEONSITE',	'NOCOST_LEAVEWHENNONBILLABLEOFFSHORE',	'NOCOST_LEAVEWHENFREEONSITE',	'NOCOST_LEAVEWHENFREEOFFSHORE',	'NOCOST_LEAVEWHENSERVICEONSITE',	'NOCOST_LEAVEWHENSERVICEOFFSHORE',	'PROJECT_SUBPRACTICE',	'PROJECT_SUBPRACTICE_DESC',	'HR_MRGID',	'PROJ_MRGID',	'ZZPROJCAT',	'DERIVED_SUITE_ID',	'DERIVED_SUITE_NAME',	'TOWER',	'INVESTMENT',	'INVESTED_FROM',	'INVESTED_TO',	'APPROVED_INVESTMENT',	'RTR_STATUS',	'RTR_DATE',	'INVESTMENT_FLAG',	'TRAINING_SKILLS',	'HOME_COST_CENTER',	'EMP_COST_CENTER_DESCRIPTION',	'GROUP_CUSTOMER_ID',	'GROUP_CUSTOMER_NAME',	'FRESHER_ENGAGEMENT_FLAG',	'BILLABLE_CATEGORY',	'ORDER_TYPE',	'ENTITY_TYPE',	'LARGE_PROGRAM',	'PRG_DIR_EMPID',	'PROGRAM',	'PGM_MGR_EMPID',	'PROJECT',	'PM_PL_EMPID',	'DM_EMPID',	'MODULE',	'MOD_EMPID',	'ROLE_DESCRIPTION',	'HOME_COMPANY_CODE',	'EMP_HOME_TOWN',	'RECENT_SKILLS',	'MSA_COUNTRY',	'MSA_COUNTRY_NAME',	'MSA_ROLE_ID',	'MSA_ROLE_DESCRIPTION',	'PROJECT_COMPANY_CODE',	'RESUME_PERCENTAGE',	'PORTFOLIO_ID',	'PORTFOLIO_NAME',	'DOMAIN_SUMMARY',	'LEGACY_PRAC_GROUP',	'LEGACY_COST_CENTER',	'LEGACY_PRACTICE',	'LEGACY_SUB_PRACTICE',	'LEGACY_SUB_PRAC_CODE',	'LEGACY_SUB_PRAC_TEXT',	'DU_PRACTICE',	'DU_SUB_PRACTICE',	'MODEL_TYPE',	'PROP_DATE',	'PROP_LVL',	'VIS_DATE',	'VIS_LVL',	'HOME_STRUCTURE',	'AGILE_FLAG',	'HOME_COUNTRY',	'HOME_GEOGRAPHY',	'PROJ_COUNTRY',	'PROJ_GEOGRAPHY',	'GEO_DU',	'FURLOUGH_WHEN_BILL_ONSITE',	'FURLOUGH_WHEN_BILL_OFFSHORE',	'FURLOUGH_WHEN_NONBILL_ONSITE',	'FURLOUGH_WHEN_NONBILL_OFFSHORE',	'FURLOUGH_WHEN_FREE_ONSITE',	'FURLOUGH_WHEN_FREE_OFFSHORE',	'FURLOUGH_WHEN_SERVICE_ONSITE',	'FURLOUGH_WHEN_SERVICE_OFFSHORE',	'DIGI_FLAG',	'FURLOUGH_FROM',	'FURLOUGH_TO',	'HR_EMP_ID',	'GIS_CATAPULT',	'SUPPORT_BILLABLE',	'COMPANY_IDENTIFICATION_FG',	'ONSITE_SUPPORT_CATEGORY',	'RM_EMP_NO',	'RM_EMP_NAME']]

#filename = 'ERD-Trajectory_{}.xlsx' .format(date.today())

Zcop3 = Zcop1.loc[Zcop1['Project2'] == 'Novartis EUS']

Zcop4 = Zcop3[['LOAD_DATE',	'COM_CODE',	'COSTCTR',	'CC_DESC',	'SAP_BU_DESC',	'SAP_VERTICAL_DESC',	'CUST_NUM',	'CUST_NAME',	'PROJ_TYPE',	'WBS_CODE',	'DOM_ID',	'DOM_DESC',	'HOME_ORGUNIT',	'HOME_ORGUNIT_DESC',	'ORG_UNIT',	'ORG_UNIT_DESCRIPTION',	'Project2', 'PROJECT_CODE',	'STAFFING_PERCENTAGE',	'BILLABILITY_STATUS',	'EMP_CODE',	'EMP_NAME', 'ERD_Date',	'PM_ID',	'PM_NAME',	'TM_EMP_NO',	'TM_NAME',	'DERIVED_EMP_CITY',	'DERIVED_EMP_STATE',	'DERIVED_EMP_COUNTRY',	'DERIVED_EMP_GEOGRAPHY',	'ONS_OFF_FLAG',	'TOTAL_DAYS',	'AREA',	'ONSITE_DAYS',	'OFFSHORE_DAYS',	'BILLABLE',	'ONSITE_BILLABLE_DAYS',	'OFFSHORE_BILLABLE_DAYS',	'NON BILLABLE',	'ONSITE_NONBILLABLE_DAYS',	'OFFSHORE_NONBILLABLE_DAYS',	'SUPPORT',	'ONSITE_SERVICE_DAYS',	'OFFSHORE_SERVICE_DAYS',	'FREE',	'ONSITE_FREE_DAYS',	'OFFSHORE_FREE_DAYS',	'LEAVE_WHEN_BILLABLE_ONSITE',	'LEAVE_WHEN_BILLABLE_OFFSHORE',	'LEAVE_WHEN_NON_BILLABLE_ONSITE',	'LEAVE_WHEN_NON_BILLABLE_OFFSHORE',	'LEAVE_WHEN_FREE_ONSITE',	'LEAVE_WHEN_FREE_OFFSHORE',	'LEAVE_WHEN_SERVICE_ONSITE',	'LEAVE_WHEN_SERVICE_OFFSHORE',	'LEAVE_WHEN_OTHERS_ONSITE',	'LEAVE_WHEN_OTHERS_OFFSHORE',	'PRACTICE',	'PRAC_CC',	'PRAC_CC_DESC',	'SAP_PRAC_DESC',	'SAP_SUBPRAC_DESC',	'SEC_PRACTICE',	'SEC_PRAC_CC',	'SEC_PRAC_CC_DESC',	'SEC_SUPID',	'SUB_GEO',	'PREVIOUS_EXP_YRS',	'PREVIOUS_EXP_MON',	'WIPRO_EXP_YRS',	'WIPRO_EXP_MON',	'SOW_NO',	'LEAVE_STAT',	'INDICATOR',	'PERSONAL_AREA',	'PERSONAL_SUB_AREA',	'SUB_PRACTICE_DUAL_CREDIT',	'SUB_PRACTICE_DUAL_CREDIT_TEXT',	'CUSTOMER_ENGAGEMENT_TYPE',	'PROJECT_CLASSIFICATION',	'CAREER_BAND',	'START_DATE',	'END_DATE',	'CRMREFNO',	'PROJSTATUS',	'LOCATION',	'EMPLOYEE_EMAIL_ID',	'DATE_OF_JOINING',	'EXPERIENCE',	'BULGE',	'ROOKIE_STATUS',	'PRIMARY_SUPERVISOR',	'PROJECT_SUPERVISOR',	'CERTIFIED_SUITE',	'CERTIFIED_SKILL',	'POTENTIAL_SUITE',	'POTENTIAL_SKILL',	'UNASSESSED_SUITE',	'UNASSESSED_SKILL',	'PROJECT_ACQUIRED_SKILL',	'FLEXPROJ',	'NOCOST_LEAVEWHENBILLABLEONSITE',	'NOCOST_LEAVEWHENBILLABLEOFFSHORE',	'NOCOST_LEAVEWHENNONBILLABLEONSITE',	'NOCOST_LEAVEWHENNONBILLABLEOFFSHORE',	'NOCOST_LEAVEWHENFREEONSITE',	'NOCOST_LEAVEWHENFREEOFFSHORE',	'NOCOST_LEAVEWHENSERVICEONSITE',	'NOCOST_LEAVEWHENSERVICEOFFSHORE',	'PROJECT_SUBPRACTICE',	'PROJECT_SUBPRACTICE_DESC',	'HR_MRGID',	'PROJ_MRGID',	'ZZPROJCAT',	'DERIVED_SUITE_ID',	'DERIVED_SUITE_NAME',	'TOWER',	'INVESTMENT',	'INVESTED_FROM',	'INVESTED_TO',	'APPROVED_INVESTMENT',	'RTR_STATUS',	'RTR_DATE',	'INVESTMENT_FLAG',	'TRAINING_SKILLS',	'HOME_COST_CENTER',	'EMP_COST_CENTER_DESCRIPTION',	'GROUP_CUSTOMER_ID',	'GROUP_CUSTOMER_NAME',	'FRESHER_ENGAGEMENT_FLAG',	'BILLABLE_CATEGORY',	'ORDER_TYPE',	'ENTITY_TYPE',	'LARGE_PROGRAM',	'PRG_DIR_EMPID',	'PROGRAM',	'PGM_MGR_EMPID',	'PROJECT',	'PM_PL_EMPID',	'DM_EMPID',	'MODULE',	'MOD_EMPID',	'ROLE_DESCRIPTION',	'HOME_COMPANY_CODE',	'EMP_HOME_TOWN',	'RECENT_SKILLS',	'MSA_COUNTRY',	'MSA_COUNTRY_NAME',	'MSA_ROLE_ID',	'MSA_ROLE_DESCRIPTION',	'PROJECT_COMPANY_CODE',	'RESUME_PERCENTAGE',	'PORTFOLIO_ID',	'PORTFOLIO_NAME',	'DOMAIN_SUMMARY',	'LEGACY_PRAC_GROUP',	'LEGACY_COST_CENTER',	'LEGACY_PRACTICE',	'LEGACY_SUB_PRACTICE',	'LEGACY_SUB_PRAC_CODE',	'LEGACY_SUB_PRAC_TEXT',	'DU_PRACTICE',	'DU_SUB_PRACTICE',	'MODEL_TYPE',	'PROP_DATE',	'PROP_LVL',	'VIS_DATE',	'VIS_LVL',	'HOME_STRUCTURE',	'AGILE_FLAG',	'HOME_COUNTRY',	'HOME_GEOGRAPHY',	'PROJ_COUNTRY',	'PROJ_GEOGRAPHY',	'GEO_DU',	'FURLOUGH_WHEN_BILL_ONSITE',	'FURLOUGH_WHEN_BILL_OFFSHORE',	'FURLOUGH_WHEN_NONBILL_ONSITE',	'FURLOUGH_WHEN_NONBILL_OFFSHORE',	'FURLOUGH_WHEN_FREE_ONSITE',	'FURLOUGH_WHEN_FREE_OFFSHORE',	'FURLOUGH_WHEN_SERVICE_ONSITE',	'FURLOUGH_WHEN_SERVICE_OFFSHORE',	'DIGI_FLAG',	'FURLOUGH_FROM',	'FURLOUGH_TO',	'HR_EMP_ID',	'GIS_CATAPULT',	'SUPPORT_BILLABLE',	'COMPANY_IDENTIFICATION_FG',	'ONSITE_SUPPORT_CATEGORY',	'RM_EMP_NO',	'RM_EMP_NAME']]

writer = pd.ExcelWriter("d:\\Python ERD.xlsx", engine='xlsxwriter')

Zcop2.to_excel(writer, sheet_name='Trajectory', index = False)
Zcop4.to_excel(writer, sheet_name='ERD', index = False)

writer.save()


